apiVersion: openchoreo.dev/v1alpha1
kind: Trait
metadata:
  name: api-configuration
  namespace: default
spec:
  schema:
    types:
      GatewayRef:
        name: "string"
        namespace: "string"

    parameters:
      # Developer-facing parameters - static across environments
      apiName: "string"
      apiVersion: "string | default=v1.0"
      context: "string" # API context path (e.g., /greeter-api, /checkout-service)
      upstreamPort: "integer | default=80" # Port on the service to route to
      upstreamBasePath: "string | default=/" # Base path on the upstream service
      operations:
        'array<map<string>> | default=[{"method": "GET", "path": "/*"}, {"method": "POST", "path": "/*"}, {"method": "PUT", "path": "/*"}, {"method": "DELETE", "path": "/*"}, {"method": "PATCH", "path": "/*"}, {"method": "OPTIONS", "path": "/*"}]'
        # Array of API operations
        # Example:
        # - method: GET
        #   path: /*
        # - method: POST
        #   path: /orders
      policies:
        "array<map<string>> | default=[]"
        # Array of policies to apply
        # Example:
        # - name: JwtAuthentication
        #   version: v0.1.0
        #   params:
        #     issuers:
        #     - ThunderKeyManager

    envOverrides:
      # Platform engineers can override per environment
      gatewayRefs:
        '[]GatewayRef | default=[{"name": "api-platform-default", "namespace": "openchoreo-data-plane"}]'
        # Gateway references - can be overridden per environment
        # Example:
        # - name: api-platform-default
        #   namespace: openchoreo-data-plane
        # - name: edge-gateway
        #   namespace: openchoreo-edge

  creates:
    # Create Backend resource that references the API gateway.
    - template:
        apiVersion: gateway.kgateway.dev/v1alpha1
        kind: Backend
        metadata:
          name: api-platform-default-gateway-router
          namespace: ${metadata.namespace}
        spec:
          type: Static
          static:
            hosts:
              - host: api-platform-default-gateway-router.openchoreo-data-plane
                port: 8080

    # Create APIConfiguration resource
    - template:
        apiVersion: api.api-platform.wso2.com/v1
        kind: APIConfiguration
        metadata:
          name: ${metadata.name}
          namespace: ${metadata.namespace}
        spec:
          gatewayRefs: ${envOverrides.gatewayRefs}
          apiConfiguration:
            version: api-platform.wso2.com/v1
            kind: http/rest
            spec:
              name: ${parameters.apiName}
              version: ${parameters.apiVersion}
              context: ${parameters.context}
              upstream:
                main:
                  url: http://${metadata.componentName}.${metadata.namespace}:${parameters.upstreamPort}${parameters.upstreamBasePath}
              policies: ${parameters.policies}
              operations: ${parameters.operations}

  patches:
    # Patch HTTPRoute to route through API Gateway instead of directly to service
    - target:
        group: gateway.networking.k8s.io
        version: v1
        kind: HTTPRoute
      operations:
        # Replace the backendRefs to route through API platform gateway router
        - op: replace
          path: /spec/rules/0/backendRefs/[?(@.name=='${metadata.componentName}')]
          value:
            group: gateway.kgateway.dev
            kind: Backend
            name: api-platform-default-gateway-router

        # Update the URLRewrite filter to rewrite to the API context
        - op: replace
          path: /spec/rules/0/filters/0/urlRewrite/path
          value:
            type: ReplacePrefixMatch
            replacePrefixMatch: ${parameters.context}
